### ISSUE TITLE
example.firebaseSDK.js is missing implementations

### ISSUE THREAD

**Issue by wmortume** [amandeepmittal/RNfirebase-chat#1]
@amandeepmittal On your _example.firebaseSDK.js_ file, you're missing the implementation for the following methods: `send()`, `refOn()`, and `refOff()`. You also only have the following methods on the [blog site](https://blog.jscrambler.com/build-a-chat-app-with-firebase-and-react-native/) but not on that file: `createAccount()`, `uploadImage()`, and `updateAvatar()`.

**Comment by amandeepmittal** [comment]
That was intentional because I picked the API Key from an ongoing project and didn't want them to be public. Also, now it seems it would be a good idea to add those methods. I am open if you want to add them via a PR to this repo 👍

**Comment by wmortume** [comment]
The thing is I wouldn't know exactly how they were implemented. I'm also using firestore instead of firebase for anything past authentication.
